In [1]:
import pandas as pd

from requests import get
from bs4 import BeautifulSoup

In [120]:
ATL.drop([87, 65, 43, 21], inplace = True)

In [121]:
ATL

,Rk,G,Date,Opp,W/L,Tm,Opp.1,ORtg,DRtg,Pace,...,STL%,BLK%,eFG%,TOV%,ORB%,FT/FGA,eFG%.1,TOV%.1,DRB%,FT/FGA.1
0,1,1,2014-10-29,TOR,L,102,109,109.1,116.6,93.5,...,6.4,12.5,.581,16.3,23.8,.113,.456,7.9,66.7,.300
1,2,2,2014-11-01,IND,W,102,92,110.0,99.2,92.7,...,10.8,12.2,.558,12.6,8.3,.362,.457,16.6,75.6,.222
2,3,3,2014-11-05,SAS,L,92,94,97.3,99.5,94.5,...,14.8,9.6,.457,11.8,20.4,.087,.486,18.1,71.1,.391
3,4,4,2014-11-07,CHO,L,119,122,104.6,107.3,94.1,...,7.0,3.9,.532,15.4,14.9,.215,.526,14.9,73.8,.206
4,5,5,2014-11-08,NYK,W,103,96,115.8,107.9,88.9,...,11.2,7.9,.463,7.6,27.9,.346,.524,14.4,69.0,.095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,78,78,2015-04-08,BRK,W,114,111,120.2,117.1,94.8,...,11.6,6.6,.564,10.2,23.3,.198,.511,10.9,68.2,.253
84,79,79,2015-04-10,CHO,W,104,80,115.0,88.4,90.5,...,11.1,7.5,.561,12.7,20.9,.146,.410,12.5,74.5,.145
85,80,80,2015-04-12,WAS,L,99,108,99.8,108.9,99.2,...,10.1,3.1,.466,10.1,15.9,.207,.512,16.4,68.9,.247
88,81,81,2015-04-13,NYK,L,108,112,118.6,122.9,91.1,...,11.0,5.8,.506,7.5,28.6,.216,.643,16.6,73.5,.169
89,82,82,2015-04-15,CHI,L,85,91,85.8,91.9,99.0,...,10.1,18.9,.435,13.6,18.9,.054,.448,19.2,82.1,.286

In [122]:
def get_url_pages():
    '''
    This function creates a list of url pages 
    of teams within a range of seasons
    '''
    urls = []
    years = ['2015', '2016', '2017', '2018']
    teams = ['ATL', 'BOS', 'BRK', 'CHO', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHO', 'POR', 'SAC', 'SAS', 'TOR', 'UTA', 'WAS']
    for year in years:
        for team in teams:
            urls.append(f"https://www.basketball-reference.com/teams/{team}/{year}/gamelog-advanced/")
    return urls

In [124]:
urls = get_url_pages()

In [125]:
urls

['https://www.basketball-reference.com/teams/ATL/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/BOS/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/BRK/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CHO/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CHI/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CLE/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DAL/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DEN/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DET/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/GSW/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/HOU/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/IND/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/LAC/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/LAL/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MEM/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIA/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIL/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIN/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/NOP/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/NYK/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/OKC/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/ORL/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/PHI/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/PHO/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/POR/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/SAC/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/SAS/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/TOR/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/UTA/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/WAS/2015/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/ATL/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/BOS/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/BRK/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CHO/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CHI/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CLE/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DAL/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DEN/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DET/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/GSW/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/HOU/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/IND/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/LAC/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/LAL/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MEM/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIA/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIL/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIN/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/NOP/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/NYK/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/OKC/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/ORL/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/PHI/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/PHO/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/POR/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/SAC/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/SAS/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/TOR/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/UTA/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/WAS/2016/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/ATL/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/BOS/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/BRK/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CHO/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CHI/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CLE/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DAL/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DEN/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DET/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/GSW/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/HOU/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/IND/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/LAC/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/LAL/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MEM/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIA/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIL/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIN/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/NOP/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/NYK/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/OKC/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/ORL/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/PHI/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/PHO/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/POR/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/SAC/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/SAS/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/TOR/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/UTA/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/WAS/2017/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/ATL/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/BOS/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/BRK/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CHO/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CHI/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/CLE/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DAL/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DEN/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/DET/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/GSW/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/HOU/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/IND/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/LAC/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/LAL/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MEM/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIA/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIL/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/MIN/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/NOP/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/NYK/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/OKC/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/ORL/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/PHI/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/PHO/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/POR/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/SAC/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/SAS/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/TOR/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/UTA/2018/gamelog-advanced/',
 'https://www.basketball-reference.com/teams/WAS/2018/gamelog-advanced/']

In [126]:
def make_soup(url=''):
    '''
    This helper function takes in a url and requests and parses HTML
    returning a soup object.
    '''
    headers = {'User-Agent': 'NLP3'} 
    response = get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')
    return soup

In [223]:
def scrape_advanced_metrics(urls=[]):
    '''
    This function takes in a list of urls
    and returns the advanced data metrics
    of each game for each team, 
    in a specified number of seasons
    '''
    total_data = pd.DataFrame()
    requests = 0
    for url in urls:
        requests += 1
        print(requests)
        soup = make_soup(url)
        team = pd.read_html(str(soup.find_all('table')[0]), header=1)[0]
        total_data = total_data.append(team, ignore_index=True)
    return total_data

In [224]:
adv_metrics = scrape_advanced_metrics(urls)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120

In [225]:
adv_metrics

,Rk,G,Date,Unnamed: 3,Opp,W/L,Tm,Opp.1,ORtg,DRtg,...,Unnamed: 18,eFG%,TOV%,ORB%,FT/FGA,Unnamed: 23,eFG%.1,TOV%.1,DRB%,FT/FGA.1
0,1,1,2014-10-29,@,TOR,L,102,109,109.1,116.6,...,NaN,.581,16.3,23.8,.113,NaN,.456,7.9,66.7,.300
1,2,2,2014-11-01,NaN,IND,W,102,92,110.0,99.2,...,NaN,.558,12.6,8.3,.362,NaN,.457,16.6,75.6,.222
2,3,3,2014-11-05,@,SAS,L,92,94,97.3,99.5,...,NaN,.457,11.8,20.4,.087,NaN,.486,18.1,71.1,.391
3,4,4,2014-11-07,@,CHO,L,119,122,104.6,107.3,...,NaN,.532,15.4,14.9,.215,NaN,.526,14.9,73.8,.206
4,5,5,2014-11-08,NaN,NYK,W,103,96,115.8,107.9,...,NaN,.463,7.6,27.9,.346,NaN,.524,14.4,69.0,.095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10795,80,80,2018-04-06,NaN,ATL,L,97,103,98.2,104.2,...,NaN,.454,11.0,17.3,.207,NaN,.551,16.8,83.7,.203
10796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Advanced,Advanced,...,NaN,Offensive Four Factors,Offensive Four Factors,Offensive Four Factors,Offensive Four Factors,NaN,Defensive Four Factors,Defensive Four Factors,Defensive Four Factors,Defensive Four Factors
10797,Rk,G,Date,NaN,Opp,W/L,Tm,Opp,ORtg,DRtg,...,NaN,eFG%,TOV%,ORB%,FT/FGA,NaN,eFG%,TOV%,DRB%,FT/FGA
10798,81,81,2018-04-10,NaN,BOS,W,113,101,113.0,101.0,...,NaN,.584,17.9,24.4,.193,NaN,.454,13.9,75.9,.253
10799,82,82,2018-04-11,@,ORL,L,92,101,95.8,105.2,...,NaN,.400,10.1,33.3,.168,NaN,.513,15.3,84.2,.286

In [226]:
adv_metrics.to_csv('advanced_metrics_data.csv')

In [227]:
teams = pd.read_csv('advanced_metrics_data.csv', index_col = 0)

In [228]:
teams

,Rk,G,Date,Unnamed: 3,Opp,W/L,Tm,Opp.1,ORtg,DRtg,...,Unnamed: 18,eFG%,TOV%,ORB%,FT/FGA,Unnamed: 23,eFG%.1,TOV%.1,DRB%,FT/FGA.1
0,1,1,2014-10-29,@,TOR,L,102,109,109.1,116.6,...,NaN,.581,16.3,23.8,.113,NaN,.456,7.9,66.7,.300
1,2,2,2014-11-01,NaN,IND,W,102,92,110.0,99.2,...,NaN,.558,12.6,8.3,.362,NaN,.457,16.6,75.6,.222
2,3,3,2014-11-05,@,SAS,L,92,94,97.3,99.5,...,NaN,.457,11.8,20.4,.087,NaN,.486,18.1,71.1,.391
3,4,4,2014-11-07,@,CHO,L,119,122,104.6,107.3,...,NaN,.532,15.4,14.9,.215,NaN,.526,14.9,73.8,.206
4,5,5,2014-11-08,NaN,NYK,W,103,96,115.8,107.9,...,NaN,.463,7.6,27.9,.346,NaN,.524,14.4,69.0,.095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10795,80,80,2018-04-06,NaN,ATL,L,97,103,98.2,104.2,...,NaN,.454,11.0,17.3,.207,NaN,.551,16.8,83.7,.203
10796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Advanced,Advanced,...,NaN,Offensive Four Factors,Offensive Four Factors,Offensive Four Factors,Offensive Four Factors,NaN,Defensive Four Factors,Defensive Four Factors,Defensive Four Factors,Defensive Four Factors
10797,Rk,G,Date,NaN,Opp,W/L,Tm,Opp,ORtg,DRtg,...,NaN,eFG%,TOV%,ORB%,FT/FGA,NaN,eFG%,TOV%,DRB%,FT/FGA
10798,81,81,2018-04-10,NaN,BOS,W,113,101,113.0,101.0,...,NaN,.584,17.9,24.4,.193,NaN,.454,13.9,75.9,.253
10799,82,82,2018-04-11,@,ORL,L,92,101,95.8,105.2,...,NaN,.400,10.1,33.3,.168,NaN,.513,15.3,84.2,.286

In [229]:
del teams['Unnamed: 3']

del teams['Unnamed: 18']

del teams['Unnamed: 23']

In [230]:
teams

,Rk,G,Date,Opp,W/L,Tm,Opp.1,ORtg,DRtg,Pace,...,STL%,BLK%,eFG%,TOV%,ORB%,FT/FGA,eFG%.1,TOV%.1,DRB%,FT/FGA.1
0,1,1,2014-10-29,TOR,L,102,109,109.1,116.6,93.5,...,6.4,12.5,.581,16.3,23.8,.113,.456,7.9,66.7,.300
1,2,2,2014-11-01,IND,W,102,92,110.0,99.2,92.7,...,10.8,12.2,.558,12.6,8.3,.362,.457,16.6,75.6,.222
2,3,3,2014-11-05,SAS,L,92,94,97.3,99.5,94.5,...,14.8,9.6,.457,11.8,20.4,.087,.486,18.1,71.1,.391
3,4,4,2014-11-07,CHO,L,119,122,104.6,107.3,94.1,...,7.0,3.9,.532,15.4,14.9,.215,.526,14.9,73.8,.206
4,5,5,2014-11-08,NYK,W,103,96,115.8,107.9,88.9,...,11.2,7.9,.463,7.6,27.9,.346,.524,14.4,69.0,.095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10795,80,80,2018-04-06,ATL,L,97,103,98.2,104.2,98.8,...,8.1,8.7,.454,11.0,17.3,.207,.551,16.8,83.7,.203
10796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Advanced,Advanced,Advanced,...,Advanced,Advanced,Offensive Four Factors,Offensive Four Factors,Offensive Four Factors,Offensive Four Factors,Defensive Four Factors,Defensive Four Factors,Defensive Four Factors,Defensive Four Factors
10797,Rk,G,Date,Opp,W/L,Tm,Opp,ORtg,DRtg,Pace,...,STL%,BLK%,eFG%,TOV%,ORB%,FT/FGA,eFG%,TOV%,DRB%,FT/FGA
10798,81,81,2018-04-10,BOS,W,113,101,113.0,101.0,100.0,...,8.0,5.6,.584,17.9,24.4,.193,.454,13.9,75.9,.253
10799,82,82,2018-04-11,ORL,L,92,101,95.8,105.2,96.0,...,5.2,2.2,.400,10.1,33.3,.168,.513,15.3,84.2,.286

In [231]:
teams.dropna(axis=0, inplace=True)

In [232]:
teams = teams.reset_index(drop=True)

In [233]:
teams.head(30)

,Rk,G,Date,Opp,W/L,Tm,Opp.1,ORtg,DRtg,Pace,...,STL%,BLK%,eFG%,TOV%,ORB%,FT/FGA,eFG%.1,TOV%.1,DRB%,FT/FGA.1
0,1,1,2014-10-29,TOR,L,102,109,109.1,116.6,93.5,...,6.4,12.5,.581,16.3,23.8,.113,.456,7.9,66.7,.300
1,2,2,2014-11-01,IND,W,102,92,110.0,99.2,92.7,...,10.8,12.2,.558,12.6,8.3,.362,.457,16.6,75.6,.222
2,3,3,2014-11-05,SAS,L,92,94,97.3,99.5,94.5,...,14.8,9.6,.457,11.8,20.4,.087,.486,18.1,71.1,.391
3,4,4,2014-11-07,CHO,L,119,122,104.6,107.3,94.1,...,7.0,3.9,.532,15.4,14.9,.215,.526,14.9,73.8,.206
4,5,5,2014-11-08,NYK,W,103,96,115.8,107.9,88.9,...,11.2,7.9,.463,7.6,27.9,.346,.524,14.4,69.0,.095
5,6,6,2014-11-10,NYK,W,91,85,104.0,97.1,87.5,...,8.0,5.3,.451,15.3,23.7,.380,.470,14.5,72.5,.084
6,7,7,2014-11-12,UTA,W,100,97,111.5,108.2,89.7,...,8.9,6.3,.572,17.7,37.1,.171,.529,10.8,80.5,.070
7,8,8,2014-11-14,MIA,W,114,103,122.5,110.6,93.1,...,10.7,9.4,.633,13.2,10.0,.253,.541,14.1,86.8,.311
8,9,9,2014-11-15,CLE,L,94,127,96.5,130.4,97.4,...,6.2,13.6,.461,15.8,23.9,.122,.650,12.0,68.4,.111
9,10,10,2014-11-18,LAL,L,109,114,119.5,125.0,91.2,...,7.7,4.3,.535,9.5,29.5,.212,.575,10.2,65.8,.161
10,11,11,2014-11-21,DET,W,99,89,109.5,98.4,90.4,...,7.7,8.1,.506,9.0,20.0,.225,.398,11.4,74.5,.277
11,12,12,2014-11-25,WAS,W,106,102,110.4,106.2,96.0,...,16.7,9.4,.465,9.1,27.9,.318,.482,17.1,66.0,.250
12,13,13,2014-11-26,TOR,L,115,126,123.9,135.8,92.8,...,2.2,7.5,.573,12.3,26.5,.256,.598,10.2,67.6,.341
13,14,14,2014-11-28,NOP,W,100,91,111.9,101.8,89.4,...,6.7,10.8,.533,17.4,29.7,.250,.444,11.1,66.0,.135
14,15,15,2014-11-29,CHO,W,105,75,118.1,84.4,88.9,...,9.0,7.7,.613,12.8,16.7,.173,.358,11.2,75.0,.136
15,16,16,2014-12-02,BOS,W,109,105,110.2,106.2,98.9,...,8.1,13.1,.591,15.4,10.8,.146,.560,19.0,75.0,.131
16,17,17,2014-12-03,MIA,W,112,102,121.7,110.9,92.0,...,9.8,2.1,.622,16.0,16.1,.270,.609,18.7,86.2,.375
17,18,18,2014-12-05,BRK,W,98,75,103.6,79.3,94.6,...,12.7,6.5,.512,9.8,12.5,.185,.394,16.1,81.6,.150
18,19,19,2014-12-07,DEN,W,96,84,103.8,90.8,92.5,...,9.7,6.9,.471,11.2,23.4,.161,.398,12.4,66.7,.108
19,20,20,2014-12-08,IND,W,108,92,109.4,93.2,98.7,...,11.1,12.3,.578,15.3,15.0,.247,.494,15.7,83.7,.107
20,Rk,G,Date,Opp,W/L,Tm,Opp,ORtg,DRtg,Pace,...,STL%,BLK%,eFG%,TOV%,ORB%,FT/FGA,eFG%,TOV%,DRB%,FT/FGA
21,21,21,2014-12-10,PHI,W,95,79,103.9,86.4,91.4,...,16.4,2.1,.473,12.6,33.3,.099,.458,18.1,83.7,.181
22,22,22,2014-12-12,ORL,W,87,81,93.5,87.0,93.1,...,12.9,5.9,.429,11.8,11.9,.256,.448,17.6,80.4,.156
23,23,23,2014-12-13,ORL,L,99,100,109.1,110.2,90.7,...,4.4,7.5,.464,9.6,23.7,.250,.568,15.3,82.1,.216
24,24,24,2014-12-15,CHI,W,93,86,99.2,91.8,93.7,...,10.7,10.9,.476,9.0,10.6,.169,.409,12.4,70.0,.108
25,25,25,2014-12-17,CLE,W,127,98,146.9,113.4,86.4,...,3.5,9.6,.750,9.8,20.7,.171,.500,8.1,77.3,.195
26,26,26,2014-12-20,HOU,W,104,97,112.1,104.5,92.8,...,7.5,20.9,.581,15.1,12.5,.243,.483,14.6,68.8,.163
27,27,27,2014-12-22,DAL,W,105,102,104.5,101.5,100.5,...,6.0,9.7,.537,15.5,15.0,.222,.494,13.2,74.0,.144
28,28,28,2014-12-23,LAC,W,107,104,113.1,110.0,94.6,...,6.3,4.8,.526,13.3,20.5,.355,.462,8.7,68.0,.207
29,29,29,2014-12-26,MIL,L,77,107,80.8,112.2,95.3,...,8.4,6.7,.434,21.1,19.0,.145,.557,14.4,83.3,.241

In [214]:
teams.tail(10)

,Rk,G,Date,Opp,W/L,Tm,Opp.1,ORtg,DRtg,Pace,...,STL%,BLK%,eFG%,TOV%,ORB%,FT/FGA,eFG%.1,TOV%.1,DRB%,FT/FGA.1
10310,74,74,2015-03-30,MIL,W,101,88,121.0,105.4,83.5,...,6.0,6.9,.513,10.9,31.6,.253,.480,11.4,69.8,.213
10311,75,75,2015-03-31,DET,L,95,105,104.4,115.4,91.0,...,8.8,0.0,.524,16.1,29.3,.083,.560,10.8,77.5,.145
10312,76,76,2015-04-04,BRK,W,131,99,138.9,105.0,94.3,...,15.9,7.0,.701,11.7,20.6,.195,.550,19.4,69.2,.138
10313,77,77,2015-04-07,PHO,W,96,69,101.7,73.1,94.4,...,9.5,6.3,.518,14.4,22.2,.120,.337,14.2,83.6,.157
10314,78,78,2015-04-08,BRK,W,114,111,120.2,117.1,94.8,...,11.6,6.6,.564,10.2,23.3,.198,.511,10.9,68.2,.253
10315,79,79,2015-04-10,CHO,W,104,80,115.0,88.4,90.5,...,11.1,7.5,.561,12.7,20.9,.146,.410,12.5,74.5,.145
10316,80,80,2015-04-12,WAS,L,99,108,99.8,108.9,99.2,...,10.1,3.1,.466,10.1,15.9,.207,.512,16.4,68.9,.247
10317,Rk,G,Date,Opp,W/L,Tm,Opp,ORtg,DRtg,Pace,...,STL%,BLK%,eFG%,TOV%,ORB%,FT/FGA,eFG%,TOV%,DRB%,FT/FGA
10318,81,81,2015-04-13,NYK,L,108,112,118.6,122.9,91.1,...,11.0,5.8,.506,7.5,28.6,.216,.643,16.6,73.5,.169
10319,82,82,2015-04-15,CHI,L,85,91,85.8,91.9,99.0,...,10.1,18.9,.435,13.6,18.9,.054,.448,19.2,82.1,.286

In [234]:
rows_to_drop = [row for row in teams[teams.Tm.isin(['Tm'])].index]

In [235]:
rows_to_drop.reverse()

In [236]:
rows_to_drop

[10317,
 10296,
 10275,
 10254,
 10231,
 10210,
 10189,
 10168,
 10145,
 10124,
 10103,
 10082,
 10059,
 10038,
 10017,
 9996,
 9973,
 9952,
 9931,
 9910,
 9887,
 9866,
 9845,
 9824,
 9801,
 9780,
 9759,
 9738,
 9715,
 9694,
 9673,
 9652,
 9629,
 9608,
 9587,
 9566,
 9543,
 9522,
 9501,
 9480,
 9457,
 9436,
 9415,
 9394,
 9371,
 9350,
 9329,
 9308,
 9285,
 9264,
 9243,
 9222,
 9199,
 9178,
 9157,
 9136,
 9113,
 9092,
 9071,
 9050,
 9027,
 9006,
 8985,
 8964,
 8941,
 8920,
 8899,
 8878,
 8855,
 8834,
 8813,
 8792,
 8769,
 8748,
 8727,
 8706,
 8683,
 8662,
 8641,
 8620,
 8597,
 8576,
 8555,
 8534,
 8511,
 8490,
 8469,
 8448,
 8425,
 8404,
 8383,
 8362,
 8339,
 8318,
 8297,
 8276,
 8253,
 8232,
 8211,
 8190,
 8167,
 8146,
 8125,
 8104,
 8081,
 8060,
 8039,
 8018,
 7995,
 7974,
 7953,
 7932,
 7909,
 7888,
 7867,
 7846,
 7823,
 7802,
 7781,
 7760,
 7737,
 7716,
 7695,
 7674,
 7651,
 7630,
 7609,
 7588,
 7565,
 7544,
 7523,
 7502,
 7479,
 7458,
 7437,
 7416,
 7393,
 7372,
 7351,
 7330,
 7307,
 7286,
 7265,
 7244,
 7221,
 7200,
 7179,
 7158,
 7135,
 7114,
 7093,
 7072,
 7049,
 7028,
 7007,
 6986,
 6963,
 6942,
 6921,
 6900,
 6877,
 6856,
 6835,
 6814,
 6791,
 6770,
 6749,
 6728,
 6705,
 6684,
 6663,
 6642,
 6619,
 6598,
 6577,
 6556,
 6533,
 6512,
 6491,
 6470,
 6447,
 6426,
 6405,
 6384,
 6361,
 6340,
 6319,
 6298,
 6275,
 6254,
 6233,
 6212,
 6189,
 6168,
 6147,
 6126,
 6103,
 6082,
 6061,
 6040,
 6017,
 5996,
 5975,
 5954,
 5931,
 5910,
 5889,
 5868,
 5845,
 5824,
 5803,
 5782,
 5759,
 5738,
 5717,
 5696,
 5673,
 5652,
 5631,
 5610,
 5587,
 5566,
 5545,
 5524,
 5501,
 5480,
 5459,
 5438,
 5415,
 5394,
 5373,
 5352,
 5329,
 5308,
 5287,
 5266,
 5243,
 5222,
 5201,
 5180,
 5157,
 5136,
 5115,
 5094,
 5071,
 5050,
 5029,
 5008,
 4985,
 4964,
 4943,
 4922,
 4899,
 4878,
 4857,
 4836,
 4813,
 4792,
 4771,
 4750,
 4727,
 4706,
 4685,
 4664,
 4641,
 4620,
 4599,
 4578,
 4555,
 4534,
 4513,
 4492,
 4469,
 4448,
 4427,
 4406,
 4383,
 4362,
 4341,
 4320,
 4297,
 4276,
 4255,
 4234,
 4211,
 4190,
 4169,
 4148,
 4125,
 4104,
 4083,
 4062,
 4039,
 4018,
 3997,
 3976,
 3953,
 3932,
 3911,
 3890,
 3867,
 3846,
 3825,
 3804,
 3781,
 3760,
 3739,
 3718,
 3695,
 3674,
 3653,
 3632,
 3609,
 3588,
 3567,
 3546,
 3523,
 3502,
 3481,
 3460,
 3437,
 3416,
 3395,
 3374,
 3351,
 3330,
 3309,
 3288,
 3265,
 3244,
 3223,
 3202,
 3179,
 3158,
 3137,
 3116,
 3093,
 3072,
 3051,
 3030,
 3007,
 2986,
 2965,
 2944,
 2921,
 2900,
 2879,
 2858,
 2835,
 2814,
 2793,
 2772,
 2749,
 2728,
 2707,
 2686,
 2663,
 2642,
 2621,
 2600,
 2577,
 2556,
 2535,
 2514,
 2491,
 2470,
 2449,
 2428,
 2405,
 2384,
 2363,
 2342,
 2319,
 2298,
 2277,
 2256,
 2233,
 2212,
 2191,
 2170,
 2147,
 2126,
 2105,
 2084,
 2061,
 2040,
 2019,
 1998,
 1975,
 1954,
 1933,
 1912,
 1889,
 1868,
 1847,
 1826,
 1803,
 1782,
 1761,
 1740,
 1717,
 1696,
 1675,
 1654,
 1631,
 1610,
 1589,
 1568,
 1545,
 1524,
 1503,
 1482,
 1459,
 1438,
 1417,
 1396,
 1373,
 1352,
 1331,
 1310,
 1287,
 1266,
 1245,
 1224,
 1201,
 1180,
 1159,
 1138,
 1115,
 1094,
 1073,
 1052,
 1029,
 1008,
 987,
 966,
 943,
 922,
 901,
 880,
 857,
 836,
 815,
 794,
 771,
 750,
 729,
 708,
 685,
 664,
 643,
 622,
 599,
 578,
 557,
 536,
 513,
 492,
 471,
 450,
 427,
 406,
 385,
 364,
 341,
 320,
 299,
 278,
 255,
 234,
 213,
 192,
 169,
 148,
 127,
 106,
 83,
 62,
 41,
 20]

In [237]:
teams.drop(rows_to_drop, inplace = True)

In [238]:
teams

,Rk,G,Date,Opp,W/L,Tm,Opp.1,ORtg,DRtg,Pace,...,STL%,BLK%,eFG%,TOV%,ORB%,FT/FGA,eFG%.1,TOV%.1,DRB%,FT/FGA.1
0,1,1,2014-10-29,TOR,L,102,109,109.1,116.6,93.5,...,6.4,12.5,.581,16.3,23.8,.113,.456,7.9,66.7,.300
1,2,2,2014-11-01,IND,W,102,92,110.0,99.2,92.7,...,10.8,12.2,.558,12.6,8.3,.362,.457,16.6,75.6,.222
2,3,3,2014-11-05,SAS,L,92,94,97.3,99.5,94.5,...,14.8,9.6,.457,11.8,20.4,.087,.486,18.1,71.1,.391
3,4,4,2014-11-07,CHO,L,119,122,104.6,107.3,94.1,...,7.0,3.9,.532,15.4,14.9,.215,.526,14.9,73.8,.206
4,5,5,2014-11-08,NYK,W,103,96,115.8,107.9,88.9,...,11.2,7.9,.463,7.6,27.9,.346,.524,14.4,69.0,.095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10314,78,78,2018-04-03,HOU,L,104,120,110.1,127.0,94.5,...,6.3,2.6,.611,17.2,7.7,.222,.607,8.6,76.7,.214
10315,79,79,2018-04-05,CLE,L,115,119,115.6,119.6,99.5,...,8.0,14.0,.548,13.0,28.6,.128,.630,15.2,85.3,.286
10316,80,80,2018-04-06,ATL,L,97,103,98.2,104.2,98.8,...,8.1,8.7,.454,11.0,17.3,.207,.551,16.8,83.7,.203
10318,81,81,2018-04-10,BOS,W,113,101,113.0,101.0,100.0,...,8.0,5.6,.584,17.9,24.4,.193,.454,13.9,75.9,.253
10319,82,82,2018-04-11,ORL,L,92,101,95.8,105.2,96.0,...,5.2,2.2,.400,10.1,33.3,.168,.513,15.3,84.2,.286